### ISSUE TITLE
Durchschnitt nicht korrekt

### ISSUE THREAD

**Issue by AlexanderTewsAltow** [Sound-Cat/Sound-Cat.github.io#1]
Durchschnitt berücksichtigt keine Klassenarbeiten

Screenshot:
<img width="1003" alt="image" src="https://user-images.githubusercontent.com/100858909/173329540-5f787280-a001-490a-84b1-52c0d27e427a.png">

**EXPECTED RESULT**: `3,21`
**ACTUAL RESULT**: `4,67`

**Comment by Sound-Cat** [comment]
Sollte nun gefixt sein
